version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    network_mode: 'host'
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: localhost
            database: boilerplate
            user: postgres
            password: postgres
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: true
